plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

host: 0.0.0.0
port: 4000

exclude:
  - 'CNAME'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'README.md'
  - 'node_modules'
  - 'package.json'
  - 'package-lock.json'
  - 'Dockerfile'
  - 'docker-compose.yml'